Sorting animation
Kirillka922/new pull request #8
Opened 2023-06-05 07:33 UTC by Kirillka922

was created the animation for sorting. In function sortChartOrder was fixed all the elements to the first position and then animate.

2023-06-05 07:34 UTC, Kirillka922 commented on src/main.js
> +}
was created the function "createNewTransform" to improve code readability.

2023-06-05 09:05 UTC, Pisyukaev reviewed
В целом, подход интересный, имеем место быть, но его не просто понять читая код. 
Еще мне не очень понравилось то, сортировка по order происходит моментально для всех элементов, а для DOM по одному элементу. 
Так же, мне удалось сделать так, что у нас запускается несколько сортировок параллельно друг другу и случается такое, что элементы просто пропадают с экрана либо наезжают друг на друга

2023-06-08 18:31 UTC, Kirillka922 commented on src/main.js
> +function replacementCord(firstColumn, secondColumn) {
Функция переброски координат, если нужно поменять местами элементы.

2023-06-08 18:38 UTC, Kirillka922 commented on src/main.js
> +  let columnsArray = Array.from(columns);
Здесь необходимо преобразовать итерируемый массив в объект, чтобы использовать map для преобразования в двумерный массив.  нам нужно предоставить нашей функции изменения в подходящем виде, так как мы храним все в прогрессе сортировки и не меняем DOM.

2023-06-08 18:39 UTC, Kirillka922 commented on src/main.js
> +    setTimeout(() => sortingElements(position, cycleNumber), 2000);
к сожалению не получилось отладить с использованием события окончания анимации. пришлось вернуться к таймеру.

2023-06-08 18:41 UTC, Kirillka922 commented on src/main.js
> +  if (isSortAttrib()) return;
Предотвращает повторное нажатие кнопки "сортировать".

2023-06-08 18:45 UTC, Kirillka922 commented on src/main.js
> +  const lengthRow = columnsArray.length - cycleNumber - 1;
при необходимости обнуляем переменные, при достижении конца строки сортировки, чтобы начать новый круг или переходим к следующей паре эл-тов.

2023-06-08 18:47 UTC, Kirillka922 commented on src/main.js
> +  if (cycleNumber > columnsArray.length - 1) {
при достижении конца цикла мы удаляем наш атрибут-индикатор состояния сортировки.

2023-06-09 08:27 UTC, Pisyukaev requested changes

2023-06-09 08:27 UTC, Pisyukaev commented on src/main.js
> +function isSortAttrib() {
исходя из названия, я бы сделал вывод, что это булева переменная, но никак не функция.

2023-06-09 08:27 UTC, Pisyukaev commented on src/main.js
> +    if (columns[i].hasAttribute("sort")) return true;
этот атрибут ты где-то используешь? Помимо проверки на то, что сортировка еще не закончена?

2023-06-09 08:27 UTC, Pisyukaev commented on src/main.js
> +  const lengthRow = columnsArray.length - cycleNumber - 1;
Что такое "конец строки сортировки"?

2023-06-09 08:27 UTC, Pisyukaev commented on src/main.js
> +    setTimeout(() => sortingElements(position, cycleNumber), 2000);
За счет чего вообще происходит анимация?

2023-06-09 08:27 UTC, Pisyukaev commented on src/main.js
> +  if (isSortAttrib()) return;
Пока идет сортировка у тебя кнопка сортировки неактивна. Но в целом да, это на всякий случай, от выстрела себе же в ногу

2023-06-09 08:27 UTC, Pisyukaev commented on src/main.js
> +    columns[i].setAttribute("sort", "true");
Зачем это все делать?

2023-06-09 08:39 UTC, Kirillka922 commented on src/main.js
> +function replacementCord(firstColumn, secondColumn) {
Мы отправляем в функцию элементы и функция достает left и переписывает другому элементу, я все это скрыл в функцию чтобы код был читабельным..  для нас это "поменять местами координаты этих элементов "

2023-06-09 08:42 UTC, Kirillka922 commented on src/main.js
> +  let columnsArray = Array.from(columns);
нет. я ошибся в формулировке . прости, я ночью это писал! Я беру итерируемый объект и трансформирую его в массив, чтобы мне были доступны методы массивов, такие как map, sort!

2023-06-09 09:03 UTC, Kirillka922 commented on src/main.js
> +    setTimeout(() => sortingElements(position, cycleNumber), 2000);
<img width="1107" alt="Снимок экрана 2023-06-09 в 16 47 51" src="https://github.com/Kirillka922/new/assets/132345382/e5e253a6-c4d9-45c5-b62e-4ae8d652676c">
Из-за того, что мы не меняем dom, у нас анимация не прерывается .. стартует с нынешнего значения left до результирующего значения left, который мы задали.

2023-06-09 09:13 UTC, Kirillka922 commented on src/main.js
> +    newColumn.style.left = `${50 * i + 8 + 5 * i}px`;
это рассчет начальных координат . 50 - ширина колонки. 8 - отступ он левого края чтобы график был не с самого начала строки.. (так как в случае первой колонки 50 * 0 + 8 - минимальный отступ. 5* i - скаждой новой колонкой нужно отступать дальше, так как предыдущий отступ съедает пространство для следующего эл-та. Так как position absolute нам пришлось выполнить начальное позиционирование эл-тов! да, можно было бы сделать симпатичнее.

2023-06-09 09:15 UTC, Kirillka922 commented on src/main.js
> +function isSortAttrib() {
да) я перепутал. нужно заменить на checkSortAttrib! да, явная оплошность.

2023-06-09 09:19 UTC, Kirillka922 commented on src/main.js
> +    if (columns[i].hasAttribute("sort")) return true;
нет. после сортировки он сразу удаляется и не мешается. это не класс и по идее, что-бы  он помешался, нужно его явно где-то умудриться прописать.. и обратиться!

2023-06-09 09:30 UTC, Kirillka922 commented on src/main.js
> +function getColumsWithSort() {
у нас работа ведется без массива с результатом сортировки, а напрямую с эл-тами на странице, то нам нужно получать нынешнюю расстановку колонок. Эта функция вернет массив с ссылками на колонки и соответствующим left ( сортировка выполнится по left). В результате следующий цикл будет работать с "прогрессом" в сортировке в виде массива колонки/left. left нужен чтобы получить по порядку элементы (от самого первого (от начала экрана) до последнего (крайнего)), и потом продолжить сортировать . Это нужно, так как скачивая эл-ты при помощи querySelectorAll, мы будем получать всегда одну картину, так как порядок dom  элементов у нас не меняется.

2023-06-09 09:41 UTC, Kirillka922 commented on src/main.js
> +    position = 1;
потому что у нас 1 элементом будет "1 - position" (0 в массиве), а второй будет "position" (1 в массиве). мы сразу начинаем с 1 чтобы было легче было описать переход но новый круг сортировки тут ((  if (position > lengthRow)  )). и у нас будет смотреться легче эта формула ((  const lengthRow = columnsArray.length - cycleNumber - 1; )) в данном случае меньше условий и нет риска выйти за пределы массива.

2023-06-09 09:47 UTC, Kirillka922 commented on src/main.js
> +    columns[i].setAttribute("sort", "true");
Чтобы ты не сломал программу. Если ты разблокируешь кнопки и будешь тестировать, то ничего не сломается при многократном нажатии на кнопку сортировки, а также на попеременные нажатия "Сортировать" и "построить график"! К примеру не сможешь создать по кнопке новый экземпляр  функции sortChartDom, который в свою очередь будет параллельно сортировать график, как было в прошлый раз.  Если есть этот атрибут, то повторных выполнений программы не будет до тех пор, пока этот атрибут не будет удален!

2023-06-09 13:38 UTC, Pisyukaev commented on src/main.js
> +function replacementCord(firstColumn, secondColumn) {
Ну мы меняем положение, не координаты X и Y

2023-06-09 13:38 UTC, Pisyukaev commented on src/main.js
> +function getColumsWithSort() {
то есть получается, что при каждой итерации ты каждый раз создаешь этот массив и сортируешь его, чтобы в дальнейшем опираться на него? 
Не слишком ли сложно? Не слишком ли много сортировок для того, чтобы сделать на основе этого простую пузырьковую сортировку?

2023-06-09 13:38 UTC, Pisyukaev commented on src/main.js
> +    if (columns[i].hasAttribute("sort")) return true;
Тогда я не понимаю, для чего ты вешаешь этот атрибут для каждого элемента?
И чтобы достать значение, тебе нужно найти все элементы, затем пройтись по всем и проставить эти трибуты... То есть это еще один проход по массиву. 
Как-то слишком много проходов по циклам во всей реализации в целом

2023-06-09 13:38 UTC, Pisyukaev commented on src/main.js
> +    position = 1;
а почему бы не сделать начальную 0, а следующую position +1? Вроде так логично

2023-06-11 12:23 UTC, Kirillka922 commented on src/main.js
> +    newColumn.style.left = `${50 * i + 8 + 5 * i}px`;
да) так и сделал

2023-06-11 12:33 UTC, Kirillka922 commented on src/main.js
> +    if (columns[i].hasAttribute("sort")) return true;
да я учет твое замечание и я теперь работаю только с 1 элементом.

2023-06-11 15:31 UTC, Kirillka922 commented on src/main.js
> +function getColumsWithSort() {
я поправил этот момент. нет лишних сортировок. массив создается только 1 раз, но к сожалению мы тут не избежим массива. но это решение лучше! Это был мой первый вариант решения программы когда было выполнено задание с рекурсией, но тогда мне показалось слишком сложно - рекурсия + параллельный массив. но сейчас уже другое дело

2023-06-11 15:37 UTC, Kirillka922 commented on src/main.js
> +    position = 1;
Я согласен. я это сделал, но это условие теперь выглядит так const lengthRow = columnsArray.length - 1 - cycleNumber - 1; я просто хотел этого избежать! но так тоже можно))

2023-06-11 15:39 UTC, Kirillka922 commented on src/main.js
> +function countFuturePosit(node) {
да) этого уже нет. код переписан

2023-06-11 15:49 UTC, Kirillka922 commented on src/main.js
> +function replacementCord(firstColumn, secondColumn) {
это поправил

2023-06-13 08:46 UTC, Pisyukaev commented on src/main.js
> +    const identForColumn = (1 + i) * 5;
а что за 5?

2023-06-13 08:46 UTC, Pisyukaev commented on src/main.js
> +  return massVals.toString() == getValidArray().toString();
это чего такое?

2023-06-13 08:46 UTC, Pisyukaev commented on src/main.js
> +  if (columns[0].hasAttribute("sort")) return true;
почему решил на первый элемент вешать?

2023-06-13 10:37 UTC, Pisyukaev commented
Я предлагаю сделать подсветку двух элементов, которые сравниваются на каждой итерации. Потому что когда подряд идут несколько элементов, которые не будут менять свое положение, складывается ощущение, что все зависает

2023-06-13 10:51 UTC, Pisyukaev commented on src/main.js
> +  let seInterv = setInterval(() => runSorting(), 1000);
Какое-то странное имя

2023-06-14 12:36 UTC, Pisyukaev commented on main.css
> +    transition: left 500ms;
👍

2023-06-14 12:36 UTC, Pisyukaev commented on main.css
> +    background-color: blue !important;
почему important?

2023-06-14 12:36 UTC, Pisyukaev commented on src/main.js
> +    const staticIndent = 6;
константы как правило пишутся капсом

2023-06-14 12:38 UTC, Pisyukaev commented on src/main.js
> +  let columnsArray = Array.from(getColumns());
почему поменял с const на let?

2023-06-14 12:42 UTC, Pisyukaev commented on src/main.js
> +function paintNextElements(...arguments) {
мне кажется, что этой функцией только переусложняется все. Как минимум из-за непонятного количество аргументов, и того, как с ними идет работв

2023-06-15 13:48 UTC, Pisyukaev commented on src/main.js
> +    const MINIMALHAIGHT = 20;
Опечатка

2023-06-15 13:48 UTC, Pisyukaev commented on src/main.js
> +      (array[i] / Math.max(...array)) * 100 + MINIMALHAIGHT
может это вынести в отдельную переменную, чтобы было поприятнее читать?

2023-06-15 13:48 UTC, Pisyukaev commented on src/main.js
> +  let sortSetInterval = setInterval(() => runSorting(), 1000);
sortSetInterval все еще не особо говорящее имя

2023-06-15 13:48 UTC, Pisyukaev commented on src/main.js
> +function removeColorElem() {
интересно =)) У тебя есть функция, которая на 2 элемента вешает классы, а эта функция проходится по всем элементам, и удаляет эти же классы. Почему так?

2023-06-15 17:17 UTC, Pisyukaev commented on src/main.js
> +  const MINIMUMHAIGHT = 20;
Все еще опечатка

2023-06-15 17:17 UTC, Pisyukaev commented on src/main.js
> +  const STATICINDENT = 6;
Есть еще один способ именования констант, это snake_case. То есть между словами ставится знак нижнего подчеркивания "_", чтобы лучше читалось

2023-06-15 17:17 UTC, Pisyukaev commented on src/main.js
> +  const STATICINDENT = 6;
Еще, сюда же, к константам.
Такие константы, как например STATICINDENT и выше, их вполне можно вынести за пределы функции. Я обычно помещаю их где-то в начале файле, после импортов.
Это не обязательно править, просто к слову.

2023-06-15 17:29 UTC, Kirillka922 reviewed
new comments

2023-06-15 17:38 UTC, Pisyukaev commented on main.css
> +    background-color: blue !important;
Что-то ничего не понятно. Давай по порядку:
1. У тебя уже есть 2 класса, column и columnSort, поэтому я не понимаю, что значит "у нас будет на 1 класс меньше"?
2. У тебя по факту и так есть два состояния у каждой ячейки, когда колонка сравнивается\переставляется, и когда она в состоянии покоя. Вполне логичное и ожидаемое поведение, что для каждого из этих состояний будет соответствующие классы

2023-06-15 17:38 UTC, Pisyukaev commented on src/main.js
> +    const haightColumn = (array[i] / Math.max(...array)) * 100 + MINIMUMHAIGHT;
опечатка

2023-06-15 17:42 UTC, Pisyukaev commented on src/main.js
> +  let columnsArray = Array.from(getColumns());
То есть ты замыкаешь эту переменную? К тому же ты сначала создаешь интервал, и только потом инициализируешь переменную. 
Что-то последовательности неочевидные

2023-06-15 17:44 UTC, Pisyukaev commented on src/main.js
> +  function runSorting() {
С этой функцией такая же история, сначала ты ее используешь в интервале, а потом объявляешь. Желательно делать все последовательно

2023-06-15 17:53 UTC, Pisyukaev commented on src/main.js
> +function replacementColumns(columnsArray, position) {
эта функция делает перестановку внутри массива, который ты передаешь первым аргументам от позиции, которую ты передаешь вторым аргументом. Давай разбираться:
1. В целом, можно обойтись и без этой функции, а делать это перемещение непосредственно в самой функции, где это надо делать
2. Второй момент, ты передаешь в эту функцию массив, который ты в самом начале создаешь, далее внутри этой функции его же преобразуешь как тебе надо, и возвращаешь уже преобразованный тот же массив. Соответственно, во-первых тебе и не обязательно ничего возвращать из функции, во-вторых на 76 строке тебе не нужно присваивать то, что возвращает функция, потому что это будет тот же самый массив

Надеюсь понятно объяснил. Если нет, пиши в телегу, обсудим

2023-06-15 17:58 UTC, Pisyukaev commented on src/main.js
> +function removeColorElem() {
Но получается, что мы делаем лишний проход по всему массиву, просто для того, чтобы убрать лишние классы. Их можно удалять с самих нод уже в тот момент, когда они больше не нужны

2023-06-16 10:05 UTC, Kirillka922 commented on main.css
> +    background-color: blue !important;
Я убрал !important. По началу я думал сделать основной класс column и 2 класса с разными цветами -синий цвет/красный цвет. у меня без important просто не работало..  скорее всего у меня был порядок стилей обратный нынешнему, так как в итоге применится тот стиль, который был назначен в таблице css последним.. important был таким костылем. сейчас все работает без него!

2023-06-16 10:45 UTC, Kirillka922 commented on src/main.js
> +  let columnsArray = Array.from(getColumns());
Да я не подумал что данные уже поменялись по ссылке и ее не нужно перезаписывать.. но мы тут получается эту переменную мутируем в чистом виде. Но это наверно можно делать, так как эта переменная как бы для внутреннего использования нашей функции. А таймер я перенес в самый конец.

2023-06-17 09:44 UTC, Kirillka922 commented on src/main.js
> +function paintNextElements(firstColumn, secondColumn) {
избавился от функции, но пока еще не знаю как принимать решение в плане создания новых. в данном случае наш код используется в одном месте и функция правда была лишней, но что касается функций checkSortAttrib (переиспользуем код в 2 местах) и функции setSortAttrib (используется в 1 месте).. нужно тоже код функции setSortAttrib перемещать в тело функций, где мы этот код используем?

2023-06-17 09:46 UTC, Kirillka922 commented on src/main.js
> +function removeColorElem() {
К сожалению такая схема не получится, так как чтобы пользователь увидел цвет элемента, то цвет должен продержаться 1 секунду до следующего цикла. я это изобразил как придумал, но пришлось прописать условия! Конечно теперь нет лишних проходов, но визуально немного код усложнился (но я создал поясняющие константы).

2023-06-17 09:47 UTC, Kirillka922 commented on src/main.js
> +  const MINIMUMHAIGHT = 20;
наверно мне нужно установить дополнение, которое будет мне помогать их искать. Я постарался просмотреть остальные переменные, но опечатки в глаза не бросаются . (

2023-06-17 09:51 UTC, Kirillka922 commented on src/main.js
> +  function runSorting() {
Перенес таймер.

2023-06-17 09:59 UTC, Kirillka922 commented on src/main.js
> +function replacementColumns(columnsArray, position) {
Да я перенес код в тело функции. остается та же проблема с пониманием когда нужно создать функцию, а когда код можно писать в теле рабочей функции как есть.

2023-06-17 10:04 UTC, Kirillka922 commented on src/main.js
> +function replacementColumns(columnsArray, position) {
Да, забыл что по ссылке меняем. Возвращать нужно только если мы не хотим мутировать данные и перед изменением клонировали.

2023-06-19 09:55 UTC, Pisyukaev reviewed
![image](https://github.com/Kirillka922/new/assets/18371315/841c04d3-00f0-41f0-becc-9c3a3e6c3391)
как у меня воспроизвелось:
отрисовал график - нажал сортировать, прошла одна итерация до конца - снова нажал на кнопку "построить график"

2023-06-19 09:55 UTC, Pisyukaev commented on src/main.js
> +      //because we need hold the color on the element for a 1 second
Комментарии оставляются над строкой(строками, блоком), к которой он относится. Так же есть много строчный комментарий

2023-06-19 09:55 UTC, Pisyukaev commented on src/main.js
> +      //after the first cycle we need to remove the color of last elements
сюда это тоже относится

2023-06-19 09:55 UTC, Pisyukaev commented on src/main.js
> +      return false;
а зачем тут false возвращать?

2023-06-19 09:55 UTC, Pisyukaev commented on src/main.js
> +        firstColumn.getBoundingClientRect().left + window.pageXOffset; //if we will have a long row of columns we need to exclude scroll
не совсем понимаю, зачем нам page offset

2023-06-19 09:55 UTC, Pisyukaev commented on src/main.js
> +    const lengthArray = columnsArray.length - 1;
эту переменную ты создаешь в самом конце функции, хотя она не изменится на протяжении всего времени, и ты выше уже используешь columnsArray.length - 1

2023-06-19 09:55 UTC, Pisyukaev commented on src/main.js
> +    const lastColumnPreviousCycle = columnsArray.length - cycleNumber + 1;
Все эти переменные, у меня вызывают вопросы, и это делает чуть более запутанным код

2023-06-20 07:35 UTC, Kirillka922 commented on src/main.js
> +      return false;
поправил) это осталось от прошлых вариантов! правильно оставить только "return"

2023-06-20 07:37 UTC, Kirillka922 commented on src/main.js
> +        firstColumn.getBoundingClientRect().left + window.pageXOffset; //if we will have a long row of columns we need to exclude scroll
Мы обсуждали. чтобы учесть прокрутку страницы по оси x. решили оставить на данный момент

2023-06-20 07:38 UTC, Kirillka922 commented on src/main.js
> +    const lengthArray = columnsArray.length - 1;
да)! Ты был прав. я ее перенес в начало

2023-06-20 08:05 UTC, Kirillka922 commented on src/main.js
> +    });
подписался на событие "transitionend" только на 1 объект, потому что они работают синхронно - нет смысла создавать 2 штуки! Без события у нас не будет заметно изменение цвета. К сожалению, без этого события и при удалении класса анимация не завершается, а прерывается.

2023-06-20 09:13 UTC, Pisyukaev reviewed
![image](https://github.com/Kirillka922/new/assets/18371315/0a602532-7f62-4cf3-b589-eedf6f423404)
Ты так и не поправил отрисовку элементов внутри блока?

2023-06-20 09:13 UTC, Pisyukaev commented on src/main.js
> +  const sortTimerId = setInterval(() => runSorting(), 1500);
мне кажется, или тут время увеличилось? 
Может это значение тоже в константу вынести?

2023-06-20 09:15 UTC, Pisyukaev commented
Я еще заметил, что у тебя перемещение элементов происходит одновременно с перекраской. Давай сделаем так, чтобы они сначала подсвечивались, а потом уже перемещались и снова перекрашивались

2023-06-20 09:40 UTC, Pisyukaev commented on src/main.js
> +    });
Кстати, я заметил, что ты только добавляешь обработчик, но нигде его не удаляешь. Это приведет к большому количеству ненужных вызовов этой функции и в последствии утечки памяти

2023-06-22 13:23 UTC, Kirillka922 commented on src/main.js
> +    });
Да) я удаляю обработчики уже после использования! Постарался это учесть! Событие и правда нужно вешать заранее, так как анимация в нашем случае может успеть выполниться до объявления события и ничего в итоге не произойдет.

2023-06-22 13:32 UTC, Kirillka922 commented on src/main.js
> +  const sortTimerId = setInterval(() => runSorting(), 1500);
Я создал константу!

2023-06-22 13:35 UTC, Kirillka922 commented on src/main.js
> +      once: true,
В этой строке удаляем обработчик после выполнения события! Также событие Формируется до нашей анимации, что не позволит его упустить и не продолжить цепочку действий!

2023-06-22 13:39 UTC, Kirillka922 commented on src/main.js
>        if (firstNumber > secondNumber) {
если у нас есть перестановка элементов, то мы создаем новое событие и после анимации удаляем класс!

2023-06-22 18:07 UTC, Pisyukaev commented on src/main.js
> +      once: true,
> В этой строке удаляем обработчик после выполнения события! Также событие Формируется до нашей анимации, что не позволит его упустить и не продолжить цепочку действий!

Мы удаляем обработчик?
Я не совсем понимаю второе предложение. Что значит "событие формируется до нашей анимации"? Это как?

2023-06-22 18:07 UTC, Pisyukaev commented on src/main.js
>        if (firstNumber > secondNumber) {
Я не вижу, чтобы мы создавали событие =)

2023-06-23 01:06 UTC, Kirillka922 commented on src/main.js
> +      once: true,
1) мы ставим событие на элемент. Оно ждет анимацию и потом выполнит наш код! Не было анимации- нет выполнения кода. У нас анимация будет через несколько строк. Мы ее не пропустим! Ты правильно заметил в прошлый раз, что если я буду подписываться на событие уже после его запуска (мы что-то меняем и и только потом подписались), то есть риск, что анимация пройдет быстрее, чем код дойдет до события и обработчик не выполнит наш код  ( как в прошлый раз, если не перемещаю элементы, то ты заметил, что у нас код остается невыполненным).

2023-06-23 01:10 UTC, Kirillka922 commented on main.css
> +    background: blue;
Нет.. тут к сожалению я снова забыл изменить.. В данный момент разницы нет.

2023-06-23 01:13 UTC, Kirillka922 commented on src/main.js
>        if (firstNumber > secondNumber) {
Этот участок объясняет концепцию программы и объясняет зачем нужно это условие. Потому что мне показалось, что код запутанный.. Я тут не рассказываю про создание события.. это и правда будет немного дальше!

2023-06-23 01:15 UTC, Kirillka922 commented on src/main.js
> +const SPEED_OF_SORTING = 1500;
я поменял на 1500 чтобы у нас только 2 события (окрас, перемещение), которые выполняются один за другим, точно поместились в диапазон и завершили свое выполнение полностью.

2023-06-23 08:07 UTC, Pisyukaev approved these changes

2023-06-23 08:10 UTC, merged